# Laboratorio 2: Producto tensorial y esfera de Bloch

## Objetivos

Con esta actividad verás la facilidad de generar un circuito de una función booleana utilizando la función clásica de `qiskit.circuit`.

## Pautas de elaboración

1. Halla el producto tensorial de matrices, en particular, de las matrices unitarias vistas en el tema 5. Encuentra:

    * $Z \otimes I \otimes Z \otimes I$
    * $I \otimes Z \otimes I \otimes Z$
    * $I \otimes Z \otimes I$

2. Calcula:

    * $\frac{3}{4}Z \otimes Z \otimes I + \frac{2}{3}Z \otimes I \otimes Z - \frac{4}{5}X \otimes Y \otimes Z - I \otimes I \otimes Z$

    * $\langle111|\frac{3}{4}Z \otimes Z \otimes I + \frac{2}{3}Z \otimes I \otimes Z - \frac{4}{5}X \otimes Y \otimes Z - I \otimes I \otimes Z|111\rangle$

3. En una sola esfera de Bloch se deben visualizar los siguientes qubits:
    - $\left|0\right\rangle$
    - $\left|1\right\rangle$
    - $\left|+\right\rangle$
    - $\left|-\right\rangle$
    - $\left|i+\right\rangle$
    - $\left|i-\right\rangle$

4. En cada ítem, crea una esfera de Bloch donde se visualicen los siguientes casos:
    - Puerta X al qubit $\left|0\right\rangle$ y al qubit $\left|1\right\rangle$
    - Puerta Y al qubit $\left|0\right\rangle$ y al qubit $\left|1\right\rangle$
    - Puerta Z al qubit $\left|0\right\rangle$ y al qubit $\left|1\right\rangle$
    - Puerta H al qubit $\left|0\right\rangle$ y al qubit $\left|1\right\rangle$


 ## Desarrollo

 En esta sección desarrollaremos los distintos ejecricios. Lo primero que haremos será importar las librerías necesaria para la implementación de los ejercicios.

 ### Librerías

 - Numpy: Operaciones matriciales
 - Qiskit: SDK de computación cuántica para implementación de circuitos y representación de estados cuánticos
 

In [4]:
# Librerías

import numpy as np

1. Halla el producto tensorial de matrices, en particular, de las matrices unitarias vistas en el tema 5. Encuentra:

    * $Z \otimes I \otimes Z \otimes I$
    * $I \otimes Z \otimes I \otimes Z$
    * $I \otimes Z \otimes I$

Definiremos primero las matrices $Z$ e $I$.

In [6]:
# Definimos la matriz de Pauli Z

# Matriz de Pauli Z (Z)
pauli_z = np.array([[1, 0], [0, -1]])

# Matriz de identidad (I)
identity_matrix = np.eye(2)

# Imprimir las matrices
print("Matriz de Pauli Z (Z):")
print(pauli_z)

print("\nMatriz de identidad (I):")
print(identity_matrix)

Matriz de Pauli Z (Z):
[[ 1  0]
 [ 0 -1]]

Matriz de identidad (I):
[[1. 0.]
 [0. 1.]]


Implementamos los cálculos haciendo uso de la función `np.kron` de Numpy, la cual nos permitirá hacer uso del producto tensorial de matrices.

* $Z \otimes I \otimes Z \otimes I$:

In [16]:
ZIZI = np.kron(np.kron(np.kron(pauli_z, identity_matrix), pauli_z), identity_matrix)

print(ZIZI)

[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1. -0.  0.  0. -0. -0.  0.  0. -0. -0.  0.  0. -0. -0.]
 [ 0.  0. -0. -1.  0.  0. -0. -0.  0.  0. -0. -0.  0.  0. -0. -0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -0. -0.  0.  0. -1. -0.  0.  0. -0. -0.  0.  0. -0. -0.]
 [ 0.  0. -0. -0.  0.  0. -0. -1.  0.  0. -0. -0.  0.  0. -0. -0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. -1. -0. -0. -0. -0. -0. -0. -0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. -0. -1. -0. -0. -0. -0. -0. -0.]
 [ 0.  0. -0. -0.  0.  0. -0. -0. -0. -0.  1.  0. -0. -0.  0.  0.]
 [ 0.  0. -0. -0.  0.  0. -0. -0. -0. -0.  0.  1. -0. -0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. -0. -0. -0. -0. -1. -0. -0. -0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. -0. -0. -0. -0. -0. -1. -0. -0.]
 [ 0.  0. -0. -0.  0.  0. -0. -0. -0. -0.  0.  0. -0. -0.  1. 

* $I \otimes Z \otimes I\otimes Z$:

In [19]:
IZIZ = np.kron(np.kron(np.kron(identity_matrix, pauli_z), identity_matrix), pauli_z)

print(IZIZ)

[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -1.  0. -0.  0. -0.  0. -0.  0. -0.  0. -0.  0. -0.  0. -0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -0.  0. -1.  0. -0.  0. -0.  0. -0.  0. -0.  0. -0.  0. -0.]
 [ 0.  0.  0.  0. -1. -0. -0. -0.  0.  0.  0.  0. -0. -0. -0. -0.]
 [ 0. -0.  0. -0. -0.  1. -0.  0.  0. -0.  0. -0. -0.  0. -0.  0.]
 [ 0.  0.  0.  0. -0. -0. -1. -0.  0.  0.  0.  0. -0. -0. -0. -0.]
 [ 0. -0.  0. -0. -0.  0. -0.  1.  0. -0.  0. -0. -0.  0. -0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -0.  0. -0.  0. -0.  0. -0.  0. -1.  0. -0.  0. -0.  0. -0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0. -0.  0. -0.  0. -0.  0. -0.  0. -0.  0. -1.  0. -0.  0. -0.]
 [ 0.  0.  0.  0. -0. -0. -0. -0.  0.  0.  0.  0. -1. -0. -0. -0.]
 [ 0. -0.  0. -0. -0.  0. -0.  0.  0. -0.  0. -0. -0.  1. -0.  0.]
 [ 0.  0.  0.  0. -0. -0. -0. -0.  0.  0.  0.  0. -0. -0. -1. 

* $I \otimes Z \otimes I$:

In [20]:
IZI = np.kron(np.kron(identity_matrix, pauli_z), identity_matrix)

print(IZI)

[[ 1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1. -0.  0.  0. -0. -0.]
 [ 0.  0. -0. -1.  0.  0. -0. -0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0. -0. -0.  0.  0. -1. -0.]
 [ 0.  0. -0. -0.  0.  0. -0. -1.]]
