# Laboratorio 2: Producto tensorial y esfera de Bloch

## Objetivos

Con esta actividad verás la facilidad de generar un circuito de una función booleana utilizando la función clásica de `qiskit.circuit`.

## Pautas de elaboración

### 1. Halla el producto tensorial de matrices, en particular, de las matrices unitarias vistas en el tema 5. Encuentra:

* $Z \otimes I \otimes Z \otimes I$
* $I \otimes Z \otimes I \otimes Z$
* $I \otimes Z \otimes I$

### 2. Calcula:

* $\frac{3}{4}Z \otimes Z \otimes I + \frac{2}{3}Z \otimes I \otimes Z - \frac{4}{5}X \otimes Y \otimes Z - I \otimes I \otimes Z$

* $\langle111|\frac{3}{4}Z \otimes Z \otimes I + \frac{2}{3}Z \otimes I \otimes Z - \frac{4}{5}X \otimes Y \otimes Z - I \otimes I \otimes Z|111\rangle$

### 3. En una sola esfera de Bloch se deben visualizar los siguientes qubits:
- $\left|0\right\rangle$
- $\left|1\right\rangle$
- $\left|+\right\rangle$
- $\left|-\right\rangle$
- $\left|i+\right\rangle$
- $\left|i-\right\rangle$
### 4. En cada ítem, crea una esfera de Bloch donde se visualicen los siguientes casos:
- Puerta X al qubit $\left|0\right\rangle$ y al qubit $\left|1\right\rangle$
- Puerta Y al qubit $\left|0\right\rangle$ y al qubit $\left|1\right\rangle$
- Puerta Z al qubit $\left|0\right\rangle$ y al qubit $\left|1\right\rangle$
- Puerta H al qubit $\left|0\right\rangle$ y al qubit $\left|1\right\rangle$


 ## Desarrollo

 En esta sección desarrollaremos los distintos ejecricios. Lo primero que haremos será importar las librerías necesaria para la implementación de los ejercicios.

 ### Librerías

 - **Numpy** : Operaciones matriciales
 - **Qiskit** : SDK de computación cuántica para implementación de circuitos y representación de estados cuánticos
 

In [1]:
# Librerías
import numpy as np
import qiskit as qk

### 1. Halla el producto tensorial de matrices, en particular, de las matrices unitarias vistas en el tema 5. Encuentra:

* $Z \otimes I \otimes Z \otimes I$
* $I \otimes Z \otimes I \otimes Z$
* $I \otimes Z \otimes I$

Definiremos primero las matrices $Z$ e $I$.

In [2]:
# Definimos la matriz de Pauli Z

# Matriz de Pauli Z (Z)
pauli_z = np.array([[1, 0], [0, -1]])

# Matriz de identidad (I)
identity = np.eye(2)

# Imprimir las matrices
print("Matriz de Pauli Z (Z):")
print(pauli_z)

print("\nMatriz de identidad (I):")
print(identity)

Matriz de Pauli Z (Z):
[[ 1  0]
 [ 0 -1]]

Matriz de identidad (I):
[[1. 0.]
 [0. 1.]]


Implementamos los cálculos haciendo uso de la función `np.kron` de Numpy, la cual nos permitirá hacer uso del producto tensorial de matrices.

* $Z \otimes I \otimes Z \otimes I$:

In [16]:
ZIZI = np.kron(np.kron(np.kron(pauli_z, identity), pauli_z), identity)

print(ZIZI)

[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1. -0.  0.  0. -0. -0.  0.  0. -0. -0.  0.  0. -0. -0.]
 [ 0.  0. -0. -1.  0.  0. -0. -0.  0.  0. -0. -0.  0.  0. -0. -0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -0. -0.  0.  0. -1. -0.  0.  0. -0. -0.  0.  0. -0. -0.]
 [ 0.  0. -0. -0.  0.  0. -0. -1.  0.  0. -0. -0.  0.  0. -0. -0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. -1. -0. -0. -0. -0. -0. -0. -0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. -0. -1. -0. -0. -0. -0. -0. -0.]
 [ 0.  0. -0. -0.  0.  0. -0. -0. -0. -0.  1.  0. -0. -0.  0.  0.]
 [ 0.  0. -0. -0.  0.  0. -0. -0. -0. -0.  0.  1. -0. -0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. -0. -0. -0. -0. -1. -0. -0. -0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. -0. -0. -0. -0. -0. -1. -0. -0.]
 [ 0.  0. -0. -0.  0.  0. -0. -0. -0. -0.  0.  0. -0. -0.  1. 

* $I \otimes Z \otimes I\otimes Z$:

In [19]:
IZIZ = np.kron(np.kron(np.kron(identity, pauli_z), identity), pauli_z)

print(IZIZ)

[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -1.  0. -0.  0. -0.  0. -0.  0. -0.  0. -0.  0. -0.  0. -0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -0.  0. -1.  0. -0.  0. -0.  0. -0.  0. -0.  0. -0.  0. -0.]
 [ 0.  0.  0.  0. -1. -0. -0. -0.  0.  0.  0.  0. -0. -0. -0. -0.]
 [ 0. -0.  0. -0. -0.  1. -0.  0.  0. -0.  0. -0. -0.  0. -0.  0.]
 [ 0.  0.  0.  0. -0. -0. -1. -0.  0.  0.  0.  0. -0. -0. -0. -0.]
 [ 0. -0.  0. -0. -0.  0. -0.  1.  0. -0.  0. -0. -0.  0. -0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -0.  0. -0.  0. -0.  0. -0.  0. -1.  0. -0.  0. -0.  0. -0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0. -0.  0. -0.  0. -0.  0. -0.  0. -0.  0. -1.  0. -0.  0. -0.]
 [ 0.  0.  0.  0. -0. -0. -0. -0.  0.  0.  0.  0. -1. -0. -0. -0.]
 [ 0. -0.  0. -0. -0.  0. -0.  0.  0. -0.  0. -0. -0.  1. -0.  0.]
 [ 0.  0.  0.  0. -0. -0. -0. -0.  0.  0.  0.  0. -0. -0. -1. 

* $I \otimes Z \otimes I$:

In [20]:
IZI = np.kron(np.kron(identity, pauli_z), identity)

print(IZI)

[[ 1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1. -0.  0.  0. -0. -0.]
 [ 0.  0. -0. -1.  0.  0. -0. -0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0. -0. -0.  0.  0. -1. -0.]
 [ 0.  0. -0. -0.  0.  0. -0. -1.]]


### 2. Calcula:


* $\frac{3}{4}Z \otimes Z \otimes I + \frac{2}{3}Z \otimes I \otimes Z - \frac{4}{5}X \otimes Y \otimes Z - I \otimes I \otimes Z$

* $\langle111|\frac{3}{4}Z \otimes Z \otimes I + \frac{2}{3}Z \otimes I \otimes Z - \frac{4}{5}X \otimes Y \otimes Z - I \otimes I \otimes Z|111\rangle$


Para el cálculo de los productos tensoriales, utilizaremos la función `np.kron` de Numpy.



* $\frac{3}{4}Z \otimes Z \otimes I + \frac{2}{3}Z \otimes I \otimes Z - \frac{4}{5}X \otimes Y \otimes Z - I \otimes I \otimes Z$:



In [22]:
# Definimos las matrices de pauli X y Y

# Matriz de Pauli X (X)
pauli_x = np.array([[0, 1], [1, 0]])

# Matriz de Pauli Y (Y)
pauli_y = np.array([[0, -1j], [1j, 0]])

# Realizamos el cálculo del ejercicio
result_1 = 3/4 * (np.kron(np.kron(pauli_z, pauli_z), identity))
result_2 = 2/3 * (np.kron(np.kron(pauli_z, pauli_z), identity))
result_3 = 4/5 * (np.kron(np.kron(pauli_x, pauli_y), pauli_z))
result_4 = (np.kron(np.kron(identity, identity), pauli_z))

result = result_1 + result_2 - result_3 - result_4

# Imprimimos el resultado
print("\nResultado:")
print(result)


Resultado:
[[ 0.41666667+0.j   0.        +0.j   0.        +0.j   0.        +0.j
   0.        +0.j   0.        +0.j   0.        +0.8j  0.        +0.j ]
 [ 0.        +0.j   2.41666667+0.j   0.        +0.j   0.        +0.j
   0.        +0.j   0.        +0.j   0.        +0.j   0.        -0.8j]
 [ 0.        +0.j   0.        +0.j  -2.41666667+0.j  -0.        +0.j
   0.        -0.8j  0.        +0.j   0.        +0.j   0.        +0.j ]
 [ 0.        +0.j   0.        +0.j  -0.        +0.j  -0.41666667+0.j
   0.        +0.j   0.        +0.8j  0.        +0.j   0.        +0.j ]
 [ 0.        +0.j   0.        +0.j   0.        +0.8j  0.        +0.j
  -2.41666667+0.j  -0.        +0.j   0.        +0.j   0.        +0.j ]
 [ 0.        +0.j   0.        +0.j   0.        +0.j   0.        -0.8j
  -0.        +0.j  -0.41666667+0.j   0.        +0.j   0.        +0.j ]
 [ 0.        -0.8j  0.        +0.j   0.        +0.j   0.        +0.j
   0.        +0.j   0.        +0.j   0.41666667+0.j   0.        +0.j ]
 [ 0.  

Una vez obtenido este resultado, lo reutilizaremos para obtener el valor esperado del observable representado por la matriz resultante para el estado $|111 \rangle$.

* $\langle111|\frac{3}{4}Z \otimes Z \otimes I + \frac{2}{3}Z \otimes I \otimes Z - \frac{4}{5}X \otimes Y \otimes Z - I \otimes I \otimes Z|111\rangle$:


In [31]:
# Definimos el vector asociado la estado 111

# Vector asociado al estado 111
state = np.kron(np.kron(np.array([[0], [1]]), np.array([[0], [1]])), np.array([[0], [1]]))
state_T = np.transpose(state)

# Imprimimos el vector
print("\nVector asociado al estado 111:")
print(state)



Vector asociado al estado 111:
[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]]


Para el cálculo del valor esperado, utilizaremos la función `np.dot` de Numpy. Esta función nos permite calcular el producto punto entre dos vectores o matrices.

In [29]:
# Calculamos el valor esperado del resultado anterior en el estado 111
# Valor esperado
expected_value = np.matmul(np.matmul(state_T, result), state)

# Imprimimos el valor esperado
print("\nValor esperado:")
print(expected_value)


Valor esperado:
[[2.41666667+0.j]]
